// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"nikhilnarayanan623/go-basic-grpc-api-gateway/pkg/api"
	"nikhilnarayanan623/go-basic-grpc-api-gateway/pkg/api/handler"
	"nikhilnarayanan623/go-basic-grpc-api-gateway/pkg/api/middleware"
	"nikhilnarayanan623/go-basic-grpc-api-gateway/pkg/clients"
	"nikhilnarayanan623/go-basic-grpc-api-gateway/pkg/config"
)

// Injectors from wire.go:

func InitializeApi(cfg *config.Config) (*http.Server, error) {
	authServiceClient, err := clients.NewAuthServiceClient(cfg)
	if err != nil {
		return nil, err
	}
	authHandler := handler.NewAuthHandler(authServiceClient)
	middlewareMiddleware := middleware.NewMiddleware(authServiceClient)
	server := http.NewServer(cfg, authHandler, middlewareMiddleware)
	return server, nil
}
